export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const FETCH_IMAGES = 'GET_IMAGES';
export const STORE_IMAGES = 'STORE_IMAGES'